### PR TITLE
update menu to work with new superlinker

### PR DESCRIPTION
**Pull request by xini**
Let me know what you think.

### CODE REVIEW

**Comment by xini** [comment]
any thoughts on this?

**Comment by xini** [comment]
Hey @dizzystuff can we please resolve this and tag a stable version with a solution for this? I don't mind what the solution is, as long as it works... ;)

**Comment by dizzystuff** [comment]
@xini as we've discussed IRL I've rebuilt this module for new superlinker, currently in two separate app folders, which now needs to be modularised. I'm not very familiar at this point with the current menus 5.x branch. I'm happy to commit this PR, and tag it as 5.0.0, and then the new build I have can be 6.0.0?

Far from perfect, but would that help on your end? Or are you ok to wait for me to update 5.x with the new build? I'm fine with either.

**Comment by xini** [comment]
@dizzystuff I'd appreciate if you could merge and tag this with 5.0 and then if you have new/better things we can create a 6.0. I already have 8 sites using this and it would get a bit hairy if I had to migrate all of them again. 
On the other hand, if you don't want to merge this, I can just create my own fork? But that's messy on my side too... Up to you.

**Pull request merged**
